#pragma once
#include <cstdint>

uint64_t ADDRESS_GAMEMANAGER = 0;
uint64_t ADDRESS_GAMERENDERER = 0;
uint64_t ADDRESS_NETWORKMANAGER = 0;
uint64_t ADDRESS_INTERFACEMANAGER = 0;
uint64_t ADDRESS_ROUNDMANAGER = 0;